package:
  name: carculator_truck
  version: 0.5.1
source:
  path: ..
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
requirements:
  host:
    - python >=3.12,<3.13
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.12,<3.13
    - carculator_utils >=1.3.6
    - prettytable
test:
  imports:
    - carculator_truck
about:
  home: https://github.com/Laboratory-for-Energy-Systems-Analysis/carculator_truck
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Prospective life cycle assessment of trucks
